### ISSUE TITLE
ContactMaterial Class 

### ISSUE THREAD

**Issue by jackfrye** [pmndrs/cannon-es-debugger#10]
This had worked fine when using non-ES official cannon.js
```
var physicsMaterial = new CANNON.Material("slipperyMaterial");
var physicsContactMaterial = new CANNON.ContactMaterial(physicsMaterial, physicsMaterial, 0.0, 0.3);
world.addContactMaterial(physicsContactMaterial);
var groundShape = new CANNON.Plane();
var groundBody = new CANNON.Body({ mass: 0}), material: physicsMaterial });
groundBody.addShape(groundShape);
groundBody.quaternion.setFromAxisAngle(new CANNON.Vec3(1,0,0),-Math.PI/2 - .30);
groundBody.position.set(0,0,0);
world.addBody(groundBody);
```

Now I am getting this error

> Uncaught TypeError: Cannot use 'in' operator to search for 'friction' in 0
>     at Function.defaults (main.js:2)
>     at new Ac (main.js:2)
>     at main.js:2
>     at main.js:2
> defaults @ main.js:2
> Ac @ main.js:2
> (anonymous) @ main.js:2
> (anonymous) @ main.js:2

Perhaps I was looking at outdated docs or examples when I pulled this in. Any ideas?

**Comment by jackfrye** [comment]
https://schteppe.github.io/cannon.js/docs/classes/ContactMaterial.html

Options is an object. Must have been looking at an outdated example.

**Comment by marcofugaro** [comment]
Yup, check out the new docs here

https://pmndrs.github.io/cannon-es/docs/classes/contactmaterial.html
