### ISSUE TITLE
Can i use it in web worker?

### ISSUE THREAD

**Issue by neciszhang** [pmndrs/cannon-es-debugger#14]
Can i use it in web worker?How to do it?

**Comment by drcmda** [comment]
use-cannon runs cannon-es in a webworker and still uses the es-debugger. https://github.com/pmndrs/use-cannon/blob/master/src/Debug.tsx

**Comment by marcofugaro** [comment]
Yes, this can be used while cannon-es is in a webworker.

If you use react, use `Debug` from use-cannon, which is already running in a web worker.

If you don't use react, check out the cannon-es [webworker](https://pmndrs.github.io/cannon-es/examples/worker) and [webworker with SharedArrayBuffer](https://pmndrs.github.io/cannon-es/examples/worker_sharedarraybuffer) examples.

**NOTE**: the library itself doesn't need to go in the serviceworker. It works with three.js which is usually on the main worker. You need to put only cannon-es in the webworker.
