### ISSUE TITLE
RaycastVehicle wheels have wrong rotation

### ISSUE THREAD

**Issue by alexandernanberg** [pmndrs/cannon-es-debugger#17]
![image](https://user-images.githubusercontent.com/8997319/138901763-fcfe9788-5b4a-4afb-823e-c9bc2709665b.png)

In this particular example they also seem to be the wrong size.

https://codesandbox.io/s/raycast-vehicle-forked-77rss?file=/src/App.js

**Comment by alexandernanberg** [comment]
When not using `use-cannon` everything looks ok, so starting to think that the issue might be there 🤔

**Comment by krispya** [comment]
Yes, that was my suspicion. That `use-cannon` is passing its rotation instead of the quaternion and its rotation was bugged.

**Comment by robksawyer** [comment]
Anyone solve this?

**Comment by marcofugaro** [comment]
This is an issue with use-cannon, see https://github.com/pmndrs/use-cannon/issues/300.

Closing.
