### ISSUE TITLE
PERFORMANCE WARNING!!! After migrated from cannon.js to cannon-es-debugger.

### ISSUE THREAD

**Issue by gonnavis** [pmndrs/cannon-es-debugger#21]
Cannon.js' `CannonDebugRenderer.js` require user to write `cannonDebugRenderer.update()`.

But `cannon-es-debugger.js` has `autoUpdate` parameter and default set to `true`, so will use inner `requestAnimationFrame` to call `update()`.

After migrated from cannon.js to cannon-es-debugger, be careful to set `autoUpdate` to `false`, or delete the old `cannonDebugRenderer.update()` in own code.

**Comment by marcofugaro** [comment]
It's not a performance problem having multiple requestAnimationFrame, but it may result in wireframes being one frame behind the body.

Do you think we should set `autoUpdate` to `false` by default?

**Comment by gonnavis** [comment]
> It's not a performance problem having multiple requestAnimationFrame, but it may result in wireframes being one frame behind the body.

Hello Marco Fugaro, I found it's really a performance problem.
Please open these two pages and wait some time ( on my pc, roughly when stats go to left ), can see the first link's fps start droping.
https://raw.githack.com/gonnavis/annihilate/8b3facdc855e83cc6e0b1a7ebd05c9b7d38fa878/index.html
https://raw.githack.com/gonnavis/annihilate/dc8a584067cf8f456426f9b9fab80fc8100245d6/index.html
![image](https://user-images.githubusercontent.com/10785634/142193684-9b7f7047-07b0-440b-bc1f-e92b0156aa53.png)
The only change between these two commit is added `autoUpdate: false`.

> Do you think we should set `autoUpdate` to `false` by default?

At first, I want to make pr or suggest a solution, but eventually I think I have not best solution now. May the best is not add autoUpdate feature at first?

**Comment by marcofugaro** [comment]
> May the best is not add autoUpdate feature at first?

Yes I agree, we'll make calling the `.update()` function mandatory.

**Comment by marcofugaro** [comment]
> Hello Marco Fugaro, I found it's really a performance problem.

Your performance problem comes from BOTH calling `.update()` and the auto-update thing, but yeah it is confusing for users.

**Comment by gonnavis** [comment]
Yes, I migrated from cannon.js, so left the `cannonDebugRenderer.update()` unremoved.

**Comment by marcofugaro** [comment]
Since version 1.0.0, the behaviour is the same as the original debugger
