### ISSUE TITLE
Incorrect Cylinder shape

### ISSUE THREAD

**Issue by tomo0613** [pmndrs/cannon-es-debugger#6]
As of new version of cannon-es Cylinder.type is equal to Shape.types.CYLINDER (as it should be).

But so far the debug-renderer handled Cylinders as ConvexPolyhedrons and now every cylinder is represented as the default "CylinderGeometry(0.5, 0.5, 1, 32)"

I'm not sure about the proper fix, but removing the body of "case CYLINDER" in "function createMesh()" leaving as 
`
case CYLINDER: \n
case CONVEXPOLYHEDRON: ...
`
solves the issue,
(the "function typeMatch()" also has not prepared to handle cylinders)

![cannon-es_debug-renderer_cylinder_issue](https://user-images.githubusercontent.com/18551999/104755180-6d752900-575a-11eb-95f9-10b06ee1100c.png)

**Comment by marcofugaro** [comment]
Thanks for the heads up @tomo0613! 

Could you test that #7 solves this issue?

**Comment by tomo0613** [comment]
I tested it.
The createMesh part works.
It wont update as the other shapes, but as I see the scale part is not implemented yet.

**Comment by marcofugaro** [comment]
> It wont update as the other shapes, but as I see the scale part is not implemented yet.

Can you elaborate? What are you doing in these specific cases?

![image](https://user-images.githubusercontent.com/7217420/104823656-1059a000-584c-11eb-939a-cb6ccfc54d4b.png)

**Comment by tomo0613** [comment]
In every case of transform (same for cylinder, polyhedron, box...) the current shape is disposed `mapElementBody.shapes.length = 0;` then a new shape is created with the modified props. so basically the shapes are replaced ( [code](https://github.com/tomo0613/offroadJS_v2/blob/f1cadb44cd0d31b67e6b6952d0db1e8b88885a33/src/mapModules/mapBuilder.ts#L488) )

**Comment by marcofugaro** [comment]
Alright, thanks for the tip, should be fixed now! Yeah the scale doesn't work for the cylinder.
