### ISSUE TITLE
Three.js r125 compatibility

### ISSUE THREAD

**Issue by hmans** [pmndrs/cannon-es-debugger#8]
![image](https://user-images.githubusercontent.com/1061/106521653-d8568c00-64de-11eb-90b8-d66a70e1dd0f.png)

Three.js r125 removed the `Geometry` class that cannon-es-debugger appears to depend on. I think for the time being it can still be imported [from examples](https://github.com/mrdoob/three.js/blob/dev/examples/jsm/deprecated/Geometry.js).

**Comment by brettkromkamp** [comment]
I second this. It would be great if cannon-es-debugger could be updated to accommodate the removal of `Geometry` (in three.js r125).

**Comment by marcofugaro** [comment]
Published `v0.1.2` 🥳

**Comment by brettkromkamp** [comment]
@marcofugaro Thank you. Works great.
